export const AUTH_ERROR_CODES = {
  USERNAME_NOT_FOUND: 'USERNAME_NOT_FOUND',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  INVALID_LOGIN_INPUT: 'INVALID_LOGIN_INPUT',
  RATE_LIMITED: 'RATE_LIMITED',
  DEVICE_REQUIRED: 'DEVICE_REQUIRED',
  EMAIL_REQUIRED: 'EMAIL_REQUIRED',
  EMAIL_INVALID: 'EMAIL_INVALID',
  VERIFICATION_REQUIRED: 'VERIFICATION_REQUIRED',
  VERIFICATION_FAILED: 'VERIFICATION_FAILED',
  REGISTRATION_BLOCKED: 'REGISTRATION_BLOCKED',
  CLAIM_INVALID: 'CLAIM_INVALID',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type AuthErrorCode = (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];
