-- Company portal staff roles + active flag
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'SENIOR_OPERATIONS_MANAGER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'SENIOR_CUSTOMER_SUPPORT';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'CXO';

ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;

DROP INDEX IF EXISTS "User_adminlike_normalized_email_unique";
